export const songs = new Map();

songs.set("All Too Well (10 minute version)", new Audio("https://upload.wikimedia.org/wikipedia/en/6/63/All_Too_Well_%2810_Minute_Version%29_by_Taylor_Swift.ogg"))
songs.set("Anti-Hero", new Audio("https://upload.wikimedia.org/wikipedia/en/a/a4/Anti-Hero_by_Taylor_Swift_%28audio%29.ogg"))
songs.set("Babe", new Audio("https://upload.wikimedia.org/wikipedia/en/c/cb/Babe_%28Taylor%27s_Version%29.ogg"))
songs.set("Bad Blood", new Audio("https://upload.wikimedia.org/wikipedia/en/7/7c/Bad_Blood.ogg"))
songs.set("Begin Again", new Audio("https://upload.wikimedia.org/wikipedia/en/5/5c/BeginAgain.ogg"))
songs.set("Blank Space", new Audio("https://upload.wikimedia.org/wikipedia/en/7/7d/Blank_Space.ogg"))
songs.set("Cardigan", new Audio("https://upload.wikimedia.org/wikipedia/en/8/86/Cardigan_by_Taylor_Swift.ogg"))
songs.set("Christmas Tree Farm", new Audio("https://upload.wikimedia.org/wikipedia/en/0/0e/Christmas_Tree_Farm_by_Taylor_Swift.ogg"))
songs.set("Cornelia Street", new Audio("https://upload.wikimedia.org/wikipedia/en/2/2a/Cornelia_Street_by_Taylor_Swift_%28song_sample%29.ogg"))
songs.set("Cowboy Like Me", new Audio("https://upload.wikimedia.org/wikipedia/en/f/f0/Cowboy_like_Me_%E2%80%93_Taylor_Swift.ogg"))
songs.set("Don’t Blame Me", new Audio("https://upload.wikimedia.org/wikipedia/en/8/8c/Don%27t_Blame_Me_by_Taylor_Swift_song_sample.ogg"))
songs.set("End Game", new Audio("https://upload.wikimedia.org/wikipedia/en/e/e5/End_Game_%28song_sample%29.ogg"))
songs.set("Evermore", new Audio("https://upload.wikimedia.org/wikipedia/en/f/fc/Evermore_by_Taylor_Swift_%28ft._Bon_Iver%29.ogg"))
songs.set("Fearless", new Audio("https://upload.wikimedia.org/wikipedia/en/b/bd/FearlessSample.ogg"))
songs.set("Fifteen", new Audio("https://upload.wikimedia.org/wikipedia/en/d/da/FifteenSample.ogg"))
songs.set("Getaway Car", new Audio("https://upload.wikimedia.org/wikipedia/en/4/42/Getaway_Car_%28Taylor_Swift_song%29_sample.ogg"))
songs.set("Gorgeous", new Audio("https://upload.wikimedia.org/wikipedia/en/2/2f/Gorgeous_-_Taylor_Swift_song_sample.ogg"))
songs.set("Hey Stephen", new Audio("https://upload.wikimedia.org/wikipedia/en/c/c6/Hey_Stephen_by_Taylor_Swift_%28sample%29.ogg"))
songs.set("Hoax", new Audio("https://upload.wikimedia.org/wikipedia/en/0/06/Hoax_by_Taylor_Swift_%28song_sample%29.ogg"))
songs.set("I Did Something Bad", new Audio("https://upload.wikimedia.org/wikipedia/en/b/b6/I_Did_Something_Bad_by_Taylor_Swif.ogg"))
songs.set("I Knew You Were Trouble", new Audio("https://upload.wikimedia.org/wikipedia/en/1/16/IKnewYouWereTrouble.ogg"))
songs.set("Illicit Affairs", new Audio("https://upload.wikimedia.org/wikipedia/en/d/de/Illicit_Affairs_by_Taylor_Swift_%28song_sample%29.ogg"))
songs.set("Invisible String", new Audio("https://upload.wikimedia.org/wikipedia/en/3/32/Invisible_String_by_Taylor_Swift.ogg"))
songs.set("Is It Over Now?", new Audio("https://upload.wikimedia.org/wikipedia/en/7/71/Is_It_Over_Now%3F_by_Taylor_Swift.ogg"))
songs.set("Labyrinth", new Audio("https://upload.wikimedia.org/wikipedia/en/d/d2/Labyrinth_by_Taylor_Swift_%28sample%29.ogg"))
songs.set("Look What You Made Me Do", new Audio("https://upload.wikimedia.org/wikipedia/en/8/8e/Look_What_You_Made_Me_Do_by_Taylor_Swift.mp3"))
songs.set("Love Story", new Audio("https://upload.wikimedia.org/wikipedia/en/8/8f/Love_Story.ogg"))
songs.set("Lover", new Audio("https://upload.wikimedia.org/wikipedia/en/2/2e/Lover_by_Taylor_Swift.mp3"))
songs.set("Marjorie", new Audio("https://upload.wikimedia.org/wikipedia/en/3/32/Marjorie_by_Taylor_Swift.ogg"))
songs.set("Maroon", new Audio("https://upload.wikimedia.org/wikipedia/en/7/7e/Maroon_by_Taylor_Swift_%28sample%29.ogg"))
songs.set("Midnight Rain", new Audio("https://upload.wikimedia.org/wikipedia/en/d/db/Midnight_Rain_by_Taylor_Swift_%28sample%29.ogg"))
songs.set("Mine", new Audio("https://upload.wikimedia.org/wikipedia/en/e/e9/Mine_Taylor_Swift.ogg"))
songs.set("Mirrorball", new Audio("https://upload.wikimedia.org/wikipedia/en/2/28/Mirrorball_by_Taylor_Swift.ogg"))
songs.set("Mr. Perfectly Fine", new Audio("https://upload.wikimedia.org/wikipedia/en/8/8a/Mr._Perfectly_Fine_by_Taylor_Swift.ogg"))
songs.set("New Year’s Day", new Audio("https://upload.wikimedia.org/wikipedia/en/1/14/New_Year%27s_Day_-_Taylor_Swift_sample.ogg"))
songs.set("...Ready for It?", new Audio("https://upload.wikimedia.org/wikipedia/en/7/7a/Ready_For_It_%28Taylor_Swift_song%29_sample.ogg"))
songs.set("Say Don’t Go", new Audio("https://upload.wikimedia.org/wikipedia/en/4/43/Say_Don%27t_Go_by_Taylor_Swift_%28song_sample%29.ogg"))
songs.set("Seven", new Audio("https://upload.wikimedia.org/wikipedia/en/a/af/Seven_by_Taylor_Swift_%28music_sample%29.ogg"))
songs.set("Sparks Fly", new Audio("https://upload.wikimedia.org/wikipedia/en/6/66/Sparks_Fly_Sample.ogg"))
songs.set("22", new Audio("https://upload.wikimedia.org/wikipedia/en/6/63/Taylor_Swift_-_22_%28song_sample%29.ogg"))
songs.set("Back to December", new Audio("https://upload.wikimedia.org/wikipedia/en/4/45/Taylor_Swift_-_Back_To_December_%28Clip%29.ogg"))
songs.set("Betty", new Audio("https://upload.wikimedia.org/wikipedia/en/2/2f/Taylor_Swift_-_Betty.ogg"))
songs.set("Cruel Summer", new Audio("https://upload.wikimedia.org/wikipedia/en/4/45/Taylor_Swift_-_Cruel_Summer_song_sample.ogg"))
songs.set("Don’t You", new Audio("https://upload.wikimedia.org/wikipedia/en/7/7a/Taylor_Swift_-_Don%27t_You_%28sample%29.ogg"))
songs.set("Enchanted", new Audio("https://upload.wikimedia.org/wikipedia/en/d/da/Taylor_Swift_-_Enchanted_%28song_sample%29.ogg"))
songs.set("I Wish You Would", new Audio("https://upload.wikimedia.org/wikipedia/en/b/b1/Taylor_Swift_-_I_Wish_You_Would_song_sample.ogg"))
songs.set("New Romantics", new Audio("https://upload.wikimedia.org/wikipedia/en/3/3d/Taylor_Swift_-_New_Romantics_sample.ogg"))
songs.set("Mean", new Audio("https://upload.wikimedia.org/wikipedia/en/a/ad/Taylor_Swift_-_Mean.ogg"))
songs.set("Out of the Woods", new Audio("https://upload.wikimedia.org/wikipedia/en/6/6c/Taylor_Swift_-_Out_of_the_Woods_song_sample.ogg"))
songs.set("Picture to Burn", new Audio("https://upload.wikimedia.org/wikipedia/en/f/f1/Taylor_Swift_-_Picture_to_Burn.ogg"))
songs.set("Red", new Audio("https://upload.wikimedia.org/wikipedia/en/3/3c/Taylor_Swift_-_Red_song_sample.ogg"))
songs.set("Slut!", new Audio("https://upload.wikimedia.org/wikipedia/en/3/30/Taylor_Swift_-_Slut%21_sample.ogg"))
songs.set("State of Grace", new Audio("https://upload.wikimedia.org/wikipedia/en/2/2a/Taylor_Swift_-_State_of_Grace_song_sample.ogg"))
songs.set("Style", new Audio("https://upload.wikimedia.org/wikipedia/en/3/3c/Taylor_Swift_-_Style_sample.ogg"))
songs.set("The Way I Loved You", new Audio("https://upload.wikimedia.org/wikipedia/en/4/4f/Taylor_Swift_-_The_Way_I_Loved_You_%28sample%29.ogg"))
songs.set("White Horse", new Audio("https://upload.wikimedia.org/wikipedia/en/9/9c/Taylor_Swift_-_White_Horse.ogg"))
songs.set("Wildest Dreams", new Audio("https://upload.wikimedia.org/wikipedia/en/1/17/Taylor_Swift_-_Wildest_Dreams.ogg"))
songs.set("Lavender Haze", new Audio("https://upload.wikimedia.org/wikipedia/en/7/77/Taylor_Swift_%22Lavender_Haze%22_sample.ogg"))
songs.set("Hits Different", new Audio("https://upload.wikimedia.org/wikipedia/en/c/cb/Taylor_Swift_%22Hits_Different%22_sample.ogg"))
songs.set("I Bet You Think About Me", new Audio("https://upload.wikimedia.org/wikipedia/en/8/81/Taylor_Swift_ft._Chris_Stapleton_-_I_Bet_You_Think_About_Me_%28Taylor%27s_Version%29.ogg"))
songs.set("Snow on the Beach", new Audio("https://en.wikipedia.org/wiki/File:Taylor_Swift_Lana_Del_Rey_%22Snow_on_the_Beach%22_Sample.ogg"))
songs.set("Teardrops on my Guitar", new Audio("https://upload.wikimedia.org/wikipedia/en/a/a1/Taylor_Swift_TeardropsonMyGuitar.ogg"))
songs.set("Tim McGraw", new Audio("https://upload.wikimedia.org/wikipedia/en/4/42/TaylorSwift_TimMcGraw.ogg"))
songs.set("The Lakes", new Audio("https://upload.wikimedia.org/wikipedia/en/5/51/The_Lakes_by_Taylor_Swift.ogg"))
songs.set("The Story of Us", new Audio("https://upload.wikimedia.org/wikipedia/en/c/c8/The_Story_of_Us_Sample.ogg"))
songs.set("We Are Never Ever Getting Back Together", new Audio("https://upload.wikimedia.org/wikipedia/en/6/67/We_Are_Never_Ever_Getting_Back_Together.ogg"))
songs.set("Welcome to New York", new Audio("https://upload.wikimedia.org/wikipedia/en/9/96/Taylor_Swift_-_Welcome_to_New_York.ogg"))
songs.set("Willow", new Audio("https://upload.wikimedia.org/wikipedia/en/9/91/Willow_by_Taylor_Swift.mp3"))
songs.set("You Belong With Me", new Audio("https://upload.wikimedia.org/wikipedia/en/5/55/You_Belong_with_Me_by_Taylor_Swift.ogg"))
songs.set("You Need to Calm Down", new Audio("https://upload.wikimedia.org/wikipedia/en/3/30/You_Need_to_Calm_Down_by_Taylor_Swift.mp3"))
songs.set("You\’re Not Sorry", new Audio("https://upload.wikimedia.org/wikipedia/en/d/d0/YoureNotSorry_sample.ogg"))
songs.set("Fortnight", new Audio("https://upload.wikimedia.org/wikipedia/en/3/3e/Fortnight_by_Taylor_Swift_feat._Post_Malone_%28sample%29.ogg"))
songs.set("So Long, London", new Audio("https://upload.wikimedia.org/wikipedia/en/c/cc/So_Long%2C_London_by_Taylor_Swift_sample.ogg"))
songs.set("So High School", new Audio("https://upload.wikimedia.org/wikipedia/en/e/e3/So_High_School_by_Taylor_Swift_%28sample%29.ogg"))

